Практическое задание к уроку 2 курса Нейронные сети

## Практическое задание

<ol>
    <li>Попробуйте обучить, нейронную сеть на Keras(рассмотренную на уроке) на датасете MNIST с другими параметрами. 
        Опишите в комментарии к уроку - какой результата вы добились от нейросети? Что помогло вам улучшить ее точность?</li>
    <li>Поработайте с документацией Keras. Попробуйте найти полезные команды Keras неразобранные на уроке.</li>
</ol>

Оценим длительность работы модели на разных параметрах. Сначала исходные:

In [1]:
# The full neural network code!
###############################
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

Using TensorFlow backend.


In [2]:
# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
#  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)


In [3]:
# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model2.h5')



Epoch 1/5
60000/60000 [==============================] - 15s 246us/step - loss: 0.3817 - accuracy: 0.8877
Epoch 2/5
60000/60000 [==============================] - 10s 170us/step - loss: 0.2171 - accuracy: 0.9350
Epoch 3/5
60000/60000 [==============================] - 11s 179us/step - loss: 0.1669 - accuracy: 0.9498
Epoch 4/5
60000/60000 [==============================] - 10s 170us/step - loss: 0.1376 - accuracy: 0.9588
Epoch 5/5
10000/10000 [==============================] - 1s 137us/step


In [4]:
# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


In [5]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


Удаление одного слоя ускорило работу модели, при хорошем результате

Уменьшим количество нейронов во внутренних слоях

In [6]:
# Build the model.
model = Sequential([
  Dense(32, activation='relu', input_shape=(784,)),
  Dense(32, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)


In [7]:
# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model2.h5')



Epoch 1/5
60000/60000 [==============================] - 12s 203us/step - loss: 0.4425 - accuracy: 0.8672
Epoch 2/5
60000/60000 [==============================] - 11s 188us/step - loss: 0.2466 - accuracy: 0.9260
Epoch 3/5
60000/60000 [==============================] - 11s 191us/step - loss: 0.1970 - accuracy: 0.9401
Epoch 4/5
60000/60000 [==============================] - 11s 181us/step - loss: 0.1654 - accuracy: 0.9494
Epoch 5/5
10000/10000 [==============================] - 1s 117us/step


In [8]:
# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


Многослойный персептрон (MLP) для мультиклассовой классификаци (softmax):

In [9]:
from keras.layers import Dropout, Activation

from keras.optimizers import SGD

In [12]:
model = Sequential()

model.add(Dense(64, activation='relu', input_dim=784))

model.add(Dropout(0.5))

model.add(Dense(64, activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(loss='categorical_crossentropy',

              optimizer=sgd,

              metrics=['accuracy'])

model.fit(  train_images, to_categorical(train_labels),

          epochs=20,

          batch_size=128)

score = model.evaluate(test_images, to_categorical(test_labels), batch_size=128)

Epoch 1/20
60000/60000 [==============================] - 4s 64us/step - loss: 1.1591 - accuracy: 0.6114
Epoch 2/20
60000/60000 [==============================] - 3s 49us/step - loss: 0.6870 - accuracy: 0.7894
Epoch 3/20
60000/60000 [==============================] - 3s 49us/step - loss: 0.5915 - accuracy: 0.8199
Epoch 4/20
60000/60000 [==============================] - 3s 52us/step - loss: 0.5459 - accuracy: 0.8370
Epoch 5/20
60000/60000 [==============================] - 3s 54us/step - loss: 0.5187 - accuracy: 0.8460
Epoch 6/20
60000/60000 [==============================] - 3s 55us/step - loss: 0.4983 - accuracy: 0.8520
Epoch 7/20
60000/60000 [==============================] - ETA: 0s - loss: 0.4785 - accuracy: 0.85 - 3s 49us/step - loss: 0.4784 - accuracy: 0.8583
Epoch 8/20
60000/60000 [==============================] - 3s 50us/step - loss: 0.4694 - accuracy: 0.8610
Epoch 9/20
60000/60000 [==============================] - 3s 56us/step - loss: 0.4557 - accuracy: 0.8658
Epoch 10/20
6

In [13]:

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


## Дополнительные материалы

<ol>
    <li>https://keras.io/</li>
</ol>

## Используемая литература 

Для подготовки данного методического пособия были использованы следующие ресурсы:
<ol>
    <li>https://keras.io/</li>
    <li>Шакла Н. — Машинное обучение и TensorFlow 2019</li>
    <li>Википедия</li>
    
</ol>