ДЗ пока не доделал, сделаю на выходных, напишу вам

Практическое задание к уроку 2 курса Нейронные сети

## Практическое задание

<ol>
    <li>Попробуйте обучить, нейронную сеть на Keras(рассмотренную на уроке) на датасете MNIST с другими параметрами. 
        Опишите в комментарии к уроку - какой результата вы добились от нейросети? Что помогло вам улучшить ее точность?</li>
    <li>Поработайте с документацией Keras. Попробуйте найти полезные команды Keras неразобранные на уроке.</li>
</ol>

Оценим длительность работы модели на разных параметрах. Сначала исходные:

In [1]:
# The full neural network code!
###############################
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

Using TensorFlow backend.


In [5]:
# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
#  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)


In [6]:
# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model2.h5')



Epoch 1/5
60000/60000 [==============================] - 10s 161us/step - loss: 0.3908 - accuracy: 0.8864
Epoch 2/5
60000/60000 [==============================] - 11s 175us/step - loss: 0.2268 - accuracy: 0.9329
Epoch 3/5
60000/60000 [==============================] - 10s 172us/step - loss: 0.1800 - accuracy: 0.9470
Epoch 4/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.1495 - accuracy: 0.9549
Epoch 5/5
10000/10000 [==============================] - 1s 100us/step


In [7]:
# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


In [8]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


Удаление одного слоя ускорило работу модели, при хорошем результате

In [5]:
# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)


In [6]:
# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model2.h5')



Epoch 1/5
60000/60000 [==============================] - 10s 161us/step - loss: 0.3908 - accuracy: 0.8864
Epoch 2/5
60000/60000 [==============================] - 11s 175us/step - loss: 0.2268 - accuracy: 0.9329
Epoch 3/5
60000/60000 [==============================] - 10s 172us/step - loss: 0.1800 - accuracy: 0.9470
Epoch 4/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.1495 - accuracy: 0.9549
Epoch 5/5
10000/10000 [==============================] - 1s 100us/step


In [7]:
# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


## Дополнительные материалы

<ol>
    <li>https://keras.io/</li>
</ol>

## Используемая литература 

Для подготовки данного методического пособия были использованы следующие ресурсы:
<ol>
    <li>https://keras.io/</li>
    <li>Шакла Н. — Машинное обучение и TensorFlow 2019</li>
    <li>Википедия</li>
    
</ol>